name: CD

on:
  push:
    branches:
      - add-cd
      - main

env:
  NODE_VERSION: '12'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: git config --global user.name "github-actions[bot]"
    - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - run: yarn install
    - run: yarn test
    - run: yarn lint
    - run: yarn analyse
    - name: Installing release tools
      run: yarn install
      working-directory: ./examples
    - name: Deploying
      run: yarn deploy
      working-directory: ./examples

