name: CD

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '12'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: git config --global user.name "github-actions[bot]"
    - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - run: yarn install
    - run: yarn test
    - run: yarn lint
    - run: yarn analyse
    - name: Installing release tools
      run: yarn install
      working-directory: ./examples
    - name: Building
      run: yarn run build
      working-directory: ./examples
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./examples/build
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'

