name: CI

on: [push]

defaults:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2
    uses: actions/setup-node@v1
    with:
      node-version: '12'
  - run: yarn install

jobs:
  test:
    - run: yarn test

  lint:
    - run: yarn lint

  analyse:
    - run: yarn analyse
