name: CI

on: [push]

env:
  node-version: '12'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      uses: actions/setup-node@v1
      with:
        node-version: ${{ node-version }}
    - run: yarn install
    - run: yarn test

  lint:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: ${{ node-version }}
      - run: yarn install
      - run: yarn lint

  analyse:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
        uses: actions/setup-node@v1
        with:
          node-version: ${{ node-version }}
      - run: yarn install
      - run: yarn analyse
