name: CI

on: [push]

env:
  NODE_VERSION: '12'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ NODE_VERSION }}
    - run: yarn install
    - run: yarn test

  lint:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ NODE_VERSION }}
      - run: yarn install
      - run: yarn lint

  analyse:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ NODE_VERSION }}
      - run: yarn install
      - run: yarn analyse
